In [1]:
import requests as rq
from bs4 import BeautifulSoup as bs
import csv
import pandas as pd

In [2]:
with open('weather.csv','w') as f:
    fnames=['temp','wind','humidity','visibility','cloud','pressure']
    writer=csv.DictWriter(f,fieldnames=fnames)
    writer.writeheader()
    for i in range(10):
        url='https://eg.freemeteo.com/weather/cairo/current-weather/location/?gid=360630&language=english&country=egypt'
        response=rq.get(url,'html.parser').text
        soup=bs(response)
        temp=soup.find('div',attrs={'class':'temp'}).get_text().split('Â°')[0]
        wind=soup.find('span',attrs={'class':'white'}).b.get_text().strip()
        details=soup.find('div',attrs={'class':'stats'}).get_text().split(' ')
        v_c=[]
        for i in details:
            if i.endswith('%'):
                humidity=i
            if i.endswith('m'):
                v_c.append(i)
            if i.endswith('mbScattered'):
                pressure=i
        humidity=humidity.split('%')[0]
        visibility=v_c[0].split('m')[0]
        cloud=v_c[1].split('m')[0]
        pressure=pressure.split('m')[0]
        data={'temp':temp,'wind':wind,'humidity':humidity,'visibility':visibility,'cloud':cloud,'pressure':pressure}
        writer.writerow(data)

In [3]:
df=pd.read_csv('weather.csv')
df

   temp  wind  humidity  visibility  cloud  pressure
0    24     6        78       10000    760    1006.0
1    24     6        78       10000    760    1006.0
2    24     6        78       10000    760    1006.0
3    24     6        78       10000    760    1006.0
4    24     6        78       10000    760    1006.0
5    24     6        78       10000    760    1006.0
6    24     6        78       10000    760    1006.0
7    24     6        78       10000    760    1006.0
8    24     6        78       10000    760    1006.0
9    24     6        78       10000    760    1006.0